version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    hostname: mongodb 

  sungoldsolar.api:
    image : sungoldsolarquotation
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongodb 
    depends_on:
      - mongodb  